# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'iOS: Increment build number and set the version to package.json version.'
  package = load_json(json_path: "./package.json")

  private_lane :inc_ver_ios do
    increment_build_number(
      xcodeproj: './ios/' + 'nativeExamples' + '.xcodeproj'
    )
    increment_version_number(
      xcodeproj: './ios/' + 'nativeExamples' + '.xcodeproj',
      version_number: package['version']
    )
  end


  desc 'Bump build numbers, and set the version to match the pacakage.json version.'
  lane :bump do
    inc_ver_ios
  end

  desc 'Build ios binaries'
  lane :build do
    gym(scheme: "./ios/nativeExamples.xcodeproj", silent: false)
  end
end
